insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (1, 'Akebia ×pentaphylla (Makino) Makino');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (2, 'Caesalpinia echinata Lam.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (3, 'Chasmanthium nitidum (Baldw.) Yates');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (4, 'Rumex arcticus Trautv. var. perlatus Hultén');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (5, 'Trifolium wormskioldii Lehm.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (6, 'Onopordum tauricum Willd.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (7, 'Acacia beckleri Tindale');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (8, 'Fendlerella utahensis (S. Watson) A. Heller');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (9, 'Verbena xutha Lehm.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (10, 'Rubus cuneifolius Pursh');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (11, 'Penstemon angustifolius Nutt. ex Pursh var. venosus (D.D. Keck) N.H. Holmgren');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (12, 'Sacciolepis striata (L.) Nash');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (13, 'Argemone pleiacantha Greene');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (14, 'Eucalyptus globulus Labill. ssp. bicostata (Maiden et al.) J.B. Kirkp.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (15, 'Aspicilia desertorum (Krempelh.) Mereschk.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (16, 'Rubus tygartensis H.A. Davis & T. Davis');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (17, 'Sapium glandulosum (L.) Morong');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (18, 'Parmelia skultii Hale');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (19, 'Centranthus ruber (L.) DC.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (20, 'Aristolochia coryi I.M. Johnst.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (21, 'Jacquemontia havanensis (Jacq.) Urb.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (22, 'Amaryllis L.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (23, 'Brodiaea terrestris Kellogg ssp. kernensis (Hoover) Niehaus');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (24, 'Cymopterus rosei (M.E. Jones ex J.M. Coult. & Rose) M.E. Jones');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (25, 'Allium sativum L.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (26, 'Callistemon phoeniceus Lindl.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (27, 'Tiarella cordifolia L.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (28, 'Glyceria grandis S. Watson var. komarovii L. Kelso');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (29, 'Pellaea glabella Mett. ex Kuhn ssp. occidentalis (E.E. Nelson) Windham');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (30, 'Atriplex bonnevillensis C.A. Hanson');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (31, 'Scutellaria drummondii Benth. var. runyonii B.L. Turner');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (32, 'Senna pendula (Humb. & Bonpl. ex Willd.) Irwin & Barneby var. pendula (Humb. & Bonpl. ex Willd.) Irwin & Barneby [excluded]');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (33, 'Fissidens littlei (R.S. Williams) Grout');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (34, 'Houttuynia cordata Thunb.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (35, 'Leavenworthia Torr.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (36, 'Astragalus xiphoides (Barneby) Barneby');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (37, 'Antennaria ×oblancifolia E.E. Nelson (pro sp.)');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (38, 'Peltigera praetextata (Flörke ex Sommerf.) Zopf');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (39, 'Ruellia nudiflora (Engelm. & A. Gray) Urb.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (40, 'Rhynchospora caduca Elliott');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (41, 'Parmotrema cristiferum (Taylor) Hale');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (42, 'Escobaria minima (Baird) D.R. Hunt');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (43, 'Hedeoma nana (Torr.) Briq. ssp. nana');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (44, 'Thalictrum thalictroides (L.) Eames & B. Boivin');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (45, 'Chrysanthemum arcticum L.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (46, 'Vaccinium cespitosum Michx.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (47, 'Cressa truxillensis Kunth');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (48, 'Allium textile A. Nelson & J.F. Macbr.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (49, 'Grindelia papposa G.L. Nesom & Suh');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (50, 'Valeriana L.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (51, 'Fritillaria striata Eastw.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (52, 'Sidalcea oregana (Nutt. ex Torr. & A. Gray) A. Gray ssp. oregana var. calva C.L. Hitchc.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (53, 'Lupinus hispanicus Boiss. & Reut. ssp. bicolor (Merino) Gladst.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (54, 'Potamogeton oblongus Viv.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (55, 'Utricularia bifida L.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (56, 'Lagophylla dichotoma Benth.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (57, 'Arctostaphylos manzanita Parry ssp. manzanita');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (58, 'Lupinus nanus Douglas ex Benth. ssp. latifolius (Benth. ex Torr.) D. Dunn');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (59, 'Salix chlorolepis Fernald');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (60, 'Alysicarpus vaginalis (L.) DC.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (61, 'Cylindropuntia (Engelm.) Kreuzinger');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (62, 'Mammillaria heyderi Muehlenpf. var. hemisphaerica Engelm.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (63, 'Chamaesyce geyeri (Engelm. & A. Gray) Small var. geyeri');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (64, 'Celosia nitida Vahl');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (65, 'Lesquerella stonensis Rollins');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (66, 'Matelea maritima (Jacq.) Woodson');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (67, 'Potamogeton crispus L.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (68, 'Heppia Nageli');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (69, 'Phemeranthus aurantiacus (Engelm.) Kiger');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (70, 'Fontinalis welchiana Allen');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (71, 'Kennedia nigricans Lindl.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (72, 'Carex abscondita Mack.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (73, 'Caltha palustris L. var. radicans (T.F. Forst.) Beck');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (74, 'Allantoparmelia (Vain.) Essl.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (75, 'Draba asterophora Payson');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (76, 'Carex muehlenbergii Schkuhr ex Willd. var. muehlenbergii');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (77, 'Cyclanthera pedata (L.) Schrad. var. pedata');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (78, 'Agnorhiza ovata (Torr. & A. Gray ex Torr.) W.A. Weber');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (79, 'Robinia hispida L. var. rosea Pursh');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (80, 'Dryopteris fuscoatra (Hillebr.) W.J. Rob.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (81, 'Pilea richardii Urb.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (82, 'Symphyotrichum lanceolatum (Willd.) G.L. Nesom ssp. hesperium (A. Gray) G.L. Nesom');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (83, 'Graphina babingtonii (Mont.) Zahlbr.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (84, 'Lycium californicum Nutt. ex A. Gray var. californicum');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (85, 'Syzygium cumini (L.) Skeels');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (86, 'Pseudoleskea patens (Lindb.) Kindb.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (87, 'Lesquerella lindheimeri (A. Gray) S. Watson');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (88, 'Luzula groenlandica Böcher');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (89, 'Silene pendula L.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (90, 'Deinandra clementina (Brandegee) B.G. Baldw.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (91, 'Lysimachia hybrida Michx.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (92, 'Cuscuta potosina Schaffn. var. globifera Yunck.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (93, 'Saponaria L.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (94, 'Physalis angustifolia Nutt.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (95, 'Caloplaca urceolata de Lesd.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (96, 'Thelypteris palustris Schott var. pubescens (G. Lawson) Fernald');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (97, 'Erigeron awapensis S.L. Welsh');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (98, 'Dendrophylax lindenii (Lindl.) Benth. ex Rolfe');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (99, 'Ulmus glabra Huds.');
insert into TIPO_DISPOSITIVO (TIPO_DISPOSITIVO_ID, NOMBRE) values (100, 'Trifolium longipes Nutt. ssp. reflexum (A. Nelson) J.M. Gillett');
